"""add category table

Revision ID: d48cd6de3c8a
Revises: 1cefe8f57afb
Create Date: 2026-03-21 22:58:28.213254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48cd6de3c8a'
down_revision: Union[str, Sequence[str], None] = '1cefe8f57afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('posts_categories_fk', 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint('posts_categories_fk', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
